---
sudo: required
services:
    - docker
language: generic
env:
    - OPTIONS=--vim-80-only
    - OPTIONS=--vim-81-only
    - OPTIONS=--neovim-only
    - OPTIONS=--python-and-linters
script: |
    ./run-tests -v $OPTIONS
